name: 'Upload to IPFS'
description: 'Upload to IPFS'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  path:
    description: 'directory path to upload'
    required: true
  host:
    description: 'IPFS host'
    required: false
    default: 'ipfs.infura.io'
  port:
    description: 'IPFS port'
    required: false
    default: '5001'
  protocol:
    description: 'IPFS protocol'
    required: false
    default: 'https'
  timeout:
    description: 'Request timeout'
    required: false
    default: '60000'
  verbose:
    description: 'Level of verbosity'
    required: false
    default: false
outputs:
  hash:
    description: 'IPFS root hash'
runs:
  using: 'node12'
  main: 'index.js'
