name: 'Upload to IPFS'
description: 'Upload to IPFS'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  path:
    description: 'directory path to upload'
    required: true
  host:
    description: 'IPFS host'
    required: false
    default: 'ipfs.komputing.org'
  port:
    description: 'IPFS host's port'
    required: false
    default: '443'
  protocol:
    description: 'IPFS host's protocol'
    required: false
    default: 'https'
outputs:
  hash:
    description: 'IPFS root's hash'
runs:
  using: 'node12'
  main: 'index.js'